### ISSUE TITLE
Jazzchords

### ISSUE THREAD

**Issue by gitaarik** [RoelofRuis/streamingmusic#1]
@RoelofRuis hey Roelof, kon ff geen andere manier vinden om je te contacten, heb volgens mij een oud nummer van je. Hier de link naar mijn chord chart project:

https://gitlab.com/gitaarik/jazzchords

je kan mij trouwens bereiken op gitaarik@posteo.net

**Comment by RoelofRuis** [comment]
Thx, ik ga het project eerdaags even bekijken! Ik zal je m'n nieuwe nummer mailen :)
